version: '2'

services:

   flask:
      image: ggriffin924/flask-alpine-docker:${DEPLOYMENT_TAG}
      restart: always
      volumes:
        - "/opt/data/images:/app/static/images"

   db:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - "/opt/data/mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: "mypasswd"
        MYSQL_DATABASE: "flask"

   proxy:
      image: foxylion/nginx-self-signed-https:latest
      restart: always
      environment:
        REMOTE_URL: "http://flask"
      ports:
        - 80:80
        - 443:443
      depends_on:
        - flask
