version: '3'

services:

   jenkins-master:
      image: myjenkins
      restart: always
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/jenkins_home:/var/jenkins_home
